### ISSUE TITLE
Transparency lost when uploading image files

### ISSUE THREAD

**Issue by nadavkav** [moodleou/moodle-qtype_ddimageortext#21]
Uploading images (PNG or GIF) with transparency channel is lost and transparency is displayed as black color.

**Comment by timhunt** [comment]
Note, this question type is now part of the standard Moodle package. It is not relevant to report bugs here. They need to go to tracker.moodle.org.

**Comment by nadavkav** [comment]
Obviously, "It is not relevant to report bugs here" as it was reported in Nov 12, 2013 :smile: 
Not sure if this issue is relevant anymore. if it does, and some teacher reports to me... I will create a new issue on the tracker.
Thank you for pointing that out.
