### ISSUE TITLE
shifted drag items during print review page

### ISSUE THREAD

**Issue by jojoob** [moodleou/moodle-qtype_ddimageortext#26]
The drag items get shifted (items not in origin position but shifted horizontal and vertical over the page, sometimes even out off the drop zone) when printing the review page. This behavior also appears on printing preview or export to pdf.
I suppose this is due to wrong values for page width and height the JavaScript uses to placing the items.

Is there a chance to easily fix this or maybe a workaround? Maybe wrapping the drop area in a box and positioning the items relative to the box instead absolute on page?
I seen YUI Library is used for rendering the question type... I never worked with this before but anyway I also disposed to help working on this problem.
In my greenness I think render the question with CSS would be a better solution - but probably to much work to change.

By the way I'm working on a moodle report plugin for quiz attempt export to pdf for archiving purposes.

Edit: same problem with ddmarker qtype: https://github.com/moodleou/moodle-qtype_ddmarker

**Comment by crazyserver** [comment]
I think this is related to issue #27, repairing JS code solved me that problem too.

**Comment by timhunt** [comment]
Thanks for diagnosing this Pau. Closing.
