### ISSUE TITLE
show full answer

### ISSUE THREAD

**Issue by hannaedelman** [moodleou/moodle-qtype_ddimageortext#29]
Hi,
When giving wrong or partial answer, it would help if the student can see the correct answer.  Either when hover on a place show the answer that goes there,  or noting on each item whether it is in its place or not.
Thanks
Hanna

**Comment by timhunt** [comment]
Note, this question type is now part of the standard Moodle package. It is not relevant to report bugs here. They need to go to tracker.moodle.org.
