### ISSUE TITLE
review miscalculate position of d'n'd elements

### ISSUE THREAD

**Issue by Tazoeur** [moodleou/moodle-qtype_ddimageortext#30]
I've seen that on the review page, the calculation of the different element are often miscalculated on the y-axis.

to solve that problem for the client, I've added a js file that trigger the event window.resize.

I assume that this is not a good solution, what do you think ?

have a nice day,
Guillaume

PS : i know that the last modification happened in 2015, but if someone wants to take the project, he'll probably look at the issues and maybe even fix them...

**Comment by timhunt** [comment]
Note, this question type is now part of the standard Moodle package. It is not relevant to report bugs here. They need to go to tracker.moodle.org.
