### ISSUE TITLE
Feature request: One Drop zone but multiple draggable items?

### ISSUE THREAD

**Issue by gjrogala** [moodleou/moodle-qtype_ddimageortext#31]
Would it be possible to have one drop zone but multiple draggable items? That would be a great feature. 

Apologies for posting this request here but the Moodle page for the plugin doesn't seem to have comments enabled.

Looking forward to a reply.

**Comment by timhunt** [comment]
This question type is now in standard Moodle, so comments should be made on moodle.org. This repo is only here to support people with very old Moodle installs.

However, what you want to do is possible and always has been. See Q5 in this demo quiz: https://qa.moodle.net/mod/quiz/view.php?id=31
